<!DOCTYPE html>
<html>
<head>
	<title>BOB System</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl();?>/public/css/style.css" />
</head>

<body>
	<ul class="menu-navigation">
		<li><a href="#">Catalog</a></li>
		<li><a href="#">Content</a></li>
		<li><a href="#">System</a></li>
		<li><a href="#">Logout</a></li>
	</ul>
	<?php echo $this->layout()->content; ?>
</body>
</html>