<div id="view-content">
	<p>View script for controller <b>Pet</b> and script/action name <b>index</b></p>
	<p><?php echo $this->mdate ?></p>
	<?php
	$this->title = "Product type";
	$this->headTitle($this->title);
?>
	<table>

	<?php
		foreach($this->productType as $productType){ ?>
			<tr>
				<td><?php echo htmlspecialchars($productType->name, ENT_QUOTES,'UTF-8'); ?></td>
			</tr>

	<?php	}
	?>
	</table>
</div>